apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Values.common.namespace}}
spec:
  selector:
    matchLabels:
      app: {{.Values.common.namespace}}
  replicas: 2
  serviceName: {{.Values.common.namespace}}
  template:
    metadata:
      labels:
        app: {{.Values.common.namespace}}
    spec:
      containers:
      - name: {{.Values.common.namespace}}
        image: {{.Values.mysql.image.repository}}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: app_db
        ports:
        - name: {{.Values.common.namespace}}
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: config-map
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            cpu: {{.Values.mysql.resources.requests.cpu}}
            memory: {{.Values.mysql.resources.requests.memory}}
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - name: config-map
        configMap:
          name:  {{.Values.common.namespace}}
      tolerations:
      - key: {{.Values.mysql.tolerations.key}}
        operator: "Equal"
        value: {{.Values.mysql.tolerations.value}}
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: {{.Values.mysql.podAntiAffinity.key}}
                    operator: In
                    values:
                    - {{.Values.mysql.podAntiAffinity.values}}
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{.Values.mysql.nodeAffinity.key}}
                    operator: In
                    values:
                    - {{.Values.mysql.nodeAffinity.values}}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
