kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{.Values.common.serviceAccountName}}
  namespace: {{.Values.common.namespace}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{.Values.common.namespace}}
  name: {{.Values.common.serviceAccountName}}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-reader-binding
  namespace: {{.Values.common.namespace}}
subjects:
- kind: ServiceAccount
  name: {{.Values.common.serviceAccountName}}
roleRef:
  kind: Role
  name: {{.Values.common.serviceAccountName}}
  apiGroup: rbac.authorization.k8s.io